// 集中重导出 wailsjs 的绑定，便于替换 mock 和统一类型
export * from '../../wailsjs/go/main/App'
export * from '../../wailsjs/runtime/runtime'

import {
  StartScan,
  CancelScan,
  GetConfig,
  GetConfigPath,
  GetDefaultReportsPath,
  SetCliPath,
  CheckCli,
  SetMaxConcurrent,
  SetToken,
  SetLocalDB,
  SetLanguage,
  SetFolderReportLocation,
  SetZipReportLocation,
  ListTasks,
  GetTask,
  GetTaskLogs,
  GetTaskResult,
  DeleteTask,
  PickDirectory,
  PickZip,
  PickExecutable,
  OpenInFolder,
  ShowItemInFolder,
  CheckCliUpdate,
  DownloadAndInstallCliUpdate,
  OpenReleasePage,
  GetRecentProjects,
  AddRecentProject,
  RemoveRecentProject,
  ClearRecentProjects,
  GetProjectScanHistory,
  GetProjectLocalDir,
  OpenProjectFolder,
  VerifyToken
} from '../../wailsjs/go/main/App'

export const api = {
  StartScan,
  CancelScan,
  GetConfig,
  GetConfigPath,
  GetDefaultReportsPath,
  SetCliPath,
  CheckCli,
  SetMaxConcurrent,
  SetToken,
  SetLocalDB,
  SetLanguage,
  SetFolderReportLocation,
  SetZipReportLocation,
  ListTasks,
  GetTask,
  GetTaskLogs,
  GetTaskResult,
  DeleteTask,
  PickDirectory,
  PickZip,
  PickExecutable,
  OpenInFolder,
  ShowItemInFolder,
  CheckCliUpdate,
  DownloadAndInstallCliUpdate,
  OpenReleasePage,
  GetRecentProjects,
  AddRecentProject,
  RemoveRecentProject,
  ClearRecentProjects,
  GetProjectScanHistory,
  GetProjectLocalDir,
  OpenProjectFolder,
  VerifyToken
}
