export default {
  common: {
    browse: 'Browse',
    verify: 'Verify',
    update: 'Update',
    cancel: 'Cancel',
    clear: 'Clear',
    remove: 'Remove',
    open: 'Open',
    close: 'Close',
    unknown: 'Unknown',
    loading: 'Loading…',
    scanning: 'Scanning…',
    saveSuccess: 'Settings saved',
    saveFailed: 'Failed to save: {msg}',
    openFailed: 'Failed to open: {msg}',
    pickDirFailed: 'Failed to pick folder: {msg}',
    pickFileFailed: 'Failed to pick file: {msg}',
    selectFailed: 'Selection failed: {msg}',
    startFailed: 'Failed to start: {msg}',
    checkUpdateFailed: 'Failed to check for updates: {msg}',
    updateFailed: 'Update failed: {msg}'
  },
  severity: {
    critical: 'Critical',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    info: 'Info',
    unknown: 'Unknown'
  },
  task: {
    status: {
      pending: 'Pending',
      running: 'Running',
      success: 'Done',
      failed: 'Failed',
      canceled: 'Canceled'
    }
  },
  router: {
    home: 'Home',
    welcome: 'Welcome to OpenSCA UI',
    scan: 'New Scan',
    tasks: 'Tasks',
    report: 'Report Details',
    settings: 'Settings',
    history: 'History'
  },
  shell: {
    nav: {
      home: 'Home',
      scan: 'New Scan',
      tasks: 'Tasks',
      history: 'History',
      settings: 'Settings'
    },
    cli: {
      notConfigured: 'CLI not configured',
      valid: 'CLI {version}',
      invalid: 'CLI invalid · {reason}',
      checkPath: 'check the path'
    },
    tip: {
      hasUpdate: 'Update available: v{version} — click to update',
      hasUpdateTitle: 'Click to go to Settings and update to v{version}',
      latest: 'Up to date',
      latestTitle: 'Up to date, click to view Settings',
      unset: 'CLI not configured, click to go to Settings',
      unsetTitle: 'opensca-cli is not configured yet, click to go to Settings'
    }
  },
  settings: {
    nav: {
      cli: 'CLI',
      general: 'General',
      vuln: 'Vulnerability DB',
      runtime: 'Runtime',
      about: 'About'
    },
    card: {
      cli: 'CLI Settings',
      general: 'General',
      vuln: 'Vulnerability DB',
      runtime: 'Runtime Settings',
      about: 'About'
    },
    saveBar: 'Save Settings',
    language: {
      label: 'Interface Language',
      desc: 'Takes effect immediately, no restart needed'
    },
    cli: {
      path: 'opensca-cli Path',
      verifyPassed: '✓ Verified',
      verifyFailed: '✗ Verification failed',
      version: 'Version: {v}'
    },
    general: {
      folderTitle: 'Report Location (Folder Scan)',
      zipTitle: 'Report Location (Archive Scan)',
      useDefault: 'Use default location',
      customPathPlaceholder: 'Custom report directory path',
      autoSubdirs1: 'The',
      autoSubdirs2: 'and',
      autoSubdirs3: 'subdirectories are created automatically under the path.',
      folderHint1: 'For folder scans, reports are generated by default in',
      folderHint2: 'in the project root. If',
      folderHint3: 'cannot be created, the default location is',
      folderHint4: '.',
      zipHint: 'The default location is',
      defaultPathExample: 'C:\\Users\\<Username>\\AppData\\Roaming\\opensca-ui\\reports'
    },
    vuln: {
      token: 'Cloud Vulnerability DB Token',
      tokenPlaceholder: 'Optional; leave empty to use only the local DB',
      verifyBtn: 'Verify',
      valid: '✓ Valid',
      invalid: '✗ Invalid',
      verifyEndpoint: 'Endpoint: {source}',
      applyCloudBefore: 'Apply for free at',
      applyCloudAfter: '',
      tokenPassHint1: 'opensca-ui passes',
      tokenPassHint2: 'to the CLI as a parameter (v2.x/v3.x supported); no manual config.json needed.',
      localDB: 'Local Vulnerability DB (db.json)',
      localDBPlaceholder: 'Optional; full path to db.json',
      localDBHint1: 'Injected via',
      localDBHint2: 'for v3.x; opensca-ui auto-generates a temporary config.json (only origin.json) and passes it to the CLI.',
      tokenEmpty: 'Token is empty',
      tokenFillFirst: 'Please fill in the token first'
    },
    runtime: {
      maxConcurrent: 'Max Concurrent Scans',
      ioHint: 'Recommended 2-4; too high will contend for IO',
      theme: 'Theme',
      themeLight: 'Light',
      themeDark: 'Dark'
    },
    about: {
      version: 'OpenSCA UI v{v}',
      builtWith: 'A desktop GUI for opensca-cli, built with Wails + Vue 3 + Naive UI.',
      configPath: 'Config file location:',
      loadFailed: 'Failed to load',
      loading: 'Loading…'
    },
    updateModal: {
      title: 'Check opensca-cli Updates',
      current: 'Current',
      latest: 'Latest',
      unknown: 'Unknown',
      hasUpdate: 'New version available',
      isLatest: 'Up to date',
      changelog: 'Changelog',
      downloadAsset: 'Download asset: {name}',
      openRelease: 'Open release page',
      downloadReplace: 'Download and Replace',
      close: 'Close',
      backupHint: 'Note: the original file is backed up as opensca-cli.exe.bak before replacement; you can restore it manually if it fails.',
      updatedTo: 'Updated to v{version}',
      backedUp: ' (old file backed up to {path})',
      configCliFirst: 'Please configure the opensca-cli path first',
      noDownloadAsset: 'No downloadable asset available, please download manually from the release page',
      noReleaseLink: 'No release link',
      missingTargetPath: 'Missing target path'
    }
  },
  home: {
    subtitle: 'One-stop open-source software composition analysis and vulnerability detection tool',
    newScan: 'New Scan',
    history: 'History',
    settings: 'Settings',
    recentProjects: 'Recently Opened Projects',
    clearAll: 'Clear All',
    clearAllConfirm: 'Clear all recent projects? This cannot be undone.',
    emptyRecent: 'No scanned projects yet',
    emptyRecentHint: 'Once you start a scan, recent projects will appear here automatically',
    scannedTimes: 'Scanned {n} times',
    archived: '{n} archived',
    openProjectFolder: 'Open project folder',
    removeFromRecent: 'Remove from recent',
    removeConfirm: 'Remove this path from recent?',
    removed: 'Removed from recent',
    listCleared: 'Recent list cleared',
    justNow: 'just now',
    minAgo: '{n} min ago',
    hourAgo: '{n} hr ago',
    dayAgo: '{n} day ago'
  },
  scan: {
    title: 'New Scan',
    projectName: 'Project Name',
    projectNamePlaceholder: 'Auto-generated from the folder name after choosing a path',
    projectNameTooltip: 'The project name binds the scan to its project and is used to group history records. It is derived from the last folder name of the selected path (or the archive name without extension) and cannot be edited.',
    taskLabel: 'Task Label (Note)',
    labelPlaceholder: 'Optional, e.g. pre-refactor scan / regression check',
    targetPath: 'Target Path',
    start: 'Start Scan',
    viewTasks: 'View Tasks',
    tokenHint: 'Token / DB is configured in Settings',
    recentTasks: 'Recent Tasks',
    noTasks: 'No tasks yet, start a scan to see it here',
    selectFirst: 'Please select a project directory first',
    taskCreated: 'Scan task created'
  },
  tasks: {
    runningTab: 'Running ({n})',
    finishedTab: 'Finished ({n})'
  },
  tasksRunning: {
    noRunning: 'No running tasks',
    cancelSent: 'Cancel request sent'
  },
  tasksFinished: {
    noFinished: 'No finished tasks'
  },
  history: {
    noHistory: 'No history yet',
    entryCount: '{n} history'
  },
  tasksHistory: {
    back: 'Back to History',
    open: 'Open',
    noFolderHistory: 'No history for this folder'
  },
  report: {
    refresh: 'Refresh',
    openReportDir: 'Open Report Folder',
    viewInBrowser: 'View in Browser',
    noReportPath: 'No corresponding report',
    htmlNotGenerated: 'HTML report not generated',
    parseFailed: 'Failed to parse report',
    cliWarningTitle: 'opensca-cli Report Notice',
    cliWarningHint: 'Tip: configure a cloud Token or local vulnerability DB in Settings so the CLI can match real vulnerability data.',
    tabVulns: 'Vulnerabilities',
    tabComponents: 'Components',
    tabLogs: 'Live Logs',
    tabRaw: 'Raw JSON',
    noReport: 'No report (the task may not be finished yet)',
    noReportSimple: 'No report',
    totalComponents: '{n} components in total',
    vulnCountShort: '{n} vulnerabilities',
    backHistory: '← Back to History',
    backRunning: '← Back to Running',
    backFinished: '← Back to Finished',
    backTasks: '← Back to Task List'
  },
  welcome: {
    title: 'Welcome to OpenSCA UI',
    subtitle: 'Before getting started, please specify the path to the opensca-cli executable',
    cliPath: 'CLI Path',
    browse: 'Browse',
    verifyEnter: 'Verify & Enter',
    verifyPassed: 'Verification passed',
    verifyFailed: 'Verification failed',
    version: 'Version: {version}',
    cliOutput: 'CLI Output',
    cliSuccess: 'CLI verified, entering the main interface',
    selectOrInputPath: 'Please select or enter a path first',
    helpBefore: 'Haven\'t downloaded opensca-cli yet? Get the version for your system from',
    helpAfter: '.'
  },
  dropzone: {
    hint: 'Drop a project folder or archive here',
    or: 'Or choose one with the buttons below',
    pickDir: 'Choose Folder',
    pickZip: 'Choose Archive',
    pastePath: 'Or paste a path:',
    use: 'Use'
  },
  stattiles: {
    components: 'Components',
    vulns: 'Vulnerabilities'
  },
  logviewer: {
    autoScroll: 'Auto-scroll',
    lines: '{n} lines',
    empty: 'No logs yet'
  },
  taskcard: {
    cancel: 'Cancel',
    viewReport: 'View Report',
    delete: 'Delete',
    finishedAt: 'Finished at {time}',
    startedAt: 'Started at {time}',
    duration: '{s}s elapsed'
  },
  vuln: {
    severityCol: 'Severity',
    riskLevel: 'Risk Level',
    vulnId: 'Vuln ID',
    cve: 'CVE',
    title: 'Title',
    affectedComponent: 'Affected Component',
    solution: 'Solution',
    name: 'Vulnerability',
    releaseDate: 'Release Date',
    exploitLevel: 'Exploit Level',
    attackType: 'Attack Type',
    description: 'Description',
    suggestion: 'Suggestion',
    searchSimplePlaceholder: 'Search vuln ID / title / component',
    severityFilter: 'Filter by severity',
    searchPlaceholder: 'Search vuln name / ID / description / suggestion',
    riskFilter: 'Filter by risk level',
    counts: '{components} components / {vulns} vulnerabilities',
    matchCount: '{n} matched',
    noMatch: 'No matching vulnerabilities',
    direct: 'Direct',
    indirect: 'Indirect',
    unknownLicense: 'Unknown',
    sevCountCritical: '{n} critical',
    sevCountHigh: '{n} high',
    sevCountMedium: '{n} medium',
    sevCountLow: '{n} low',
    sevCountInfo: '{n} info',
    exploit: {
      easy: 'Easy',
      medium: 'Medium',
      hard: 'Hard',
      unknown: 'Unknown'
    }
  },
  vulnDetail: {
    vulnId: 'Vuln ID',
    severity: 'Severity',
    cve: 'CVE ID',
    cwe: 'CWE ID',
    source: 'Source',
    purl: 'PURL',
    desc: 'Description',
    suggestion: 'Suggestion',
    refs: 'References',
    noRefs: 'No references',
    noDesc: '(No description)',
    noSuggestion: '(No suggestion)'
  }
}
